# =====================================================
# Dataset
# =====================================================
ds_name: "seaice_AMSR-2_OSI-408" # Name for dataset
version: 1.0 # Update this value if any changes are made to this file
array_precision: float32
remove_nan_days_from_data: False # Remove empty days from data when aggregating
do_monthly_aggregation: True
skipna_in_mean: True # Controls skipna when calculating monthly mean
save_binary: True
save_netcdf: True
monthly_tolerance: 8 # Defines the range of days to look for data around the start of the month (exclusive)

# =====================================================
# Solr
# =====================================================
solr_host_local: http://localhost:8983/solr/ # doesn't change if following standard Solr setup
solr_host_aws: http://ec2-3-16-187-19.us-east-2.compute.amazonaws.com:8983/solr/
solr_collection_name: ecco_datasets # doesn't change

# =====================================================
# AWS
# =====================================================
source_bucket: ecco-ames
target_bucket: ecco-ames
s3_aggregated_path: aggregated/
