# =====================================================
# PODAAC
# =====================================================
# PODAAC explicitly expects this date format
start: "20160101T00:00:01Z" # yyyymmddThh:mm:ssZ
end: "NOW" # yyyymmddThh:mm:ssZ for specific date or "NOW" for...now 
user: anonymous # does not change
host: https://podaac.jpl.nasa.gov/ws/search/granule/?format=atom&pretty=false&itemsPerPage=300000 # does not change
date_regex: "%Y-%m-%dT%H:%M:%SZ" # does not change

# =====================================================
# Dataset
# =====================================================
ds_name: "sss_SMAP_RSS_L3_SSS_SMI_MONTHLY_V4" # Name for dataset
harvester_type: "podaac"
podaac_id: "PODAAC-SMP40-3SMCS"
aggregated: false # if data is available aggregated
data_time_scale: "monthly" # daily or monthly
date_format: "yyyy_mm" # format of date in file name ex: yyyymmdd
fields:
  [
    {
      name: sss_smap_40km,
      long_name: SMAP sea surface salinity,
      standard_name: sea_surface_salinity,
      units: 1e-3,
    },
    {
      name: sss_smap_uncertainty,
      long_name: estimated empirical uncertainty of SMAP sea surface salinity smoothed to approx 70km resolution,
      standard_name: " ",
      units: 1e-3,
    },
  ]

# new_data_attrs:
original_dataset_title: RSS SMAP Level 3 Sea Surface Salinity Standard Mapped Image Monthly V4.0 Validated Dataset
original_dataset_short_name: SMAP_RSS_L3_SSS_SMI_MONTHLY_V4
original_dataset_url: https://podaac.jpl.nasa.gov/dataset/SMAP_RSS_L3_SSS_SMI_MONTHLY_V4
original_dataset_reference: http://smap.jpl.nasa.gov/
original_dataset_doi: 10.5067/SMP40-3SMCS

# =====================================================
# Solr
# =====================================================
solr_host_local: http://localhost:8983/solr/ # doesn't change if following standard Solr setup
solr_host_aws: http://ec2-3-16-187-19.us-east-2.compute.amazonaws.com:8983/solr/
solr_collection_name: ecco_datasets # doesn't change

# =====================================================
# AWS
# =====================================================
target_bucket_name: ecco-preprocess
