# =====================================================
# PODAAC
# =====================================================
# PODAAC explicitly expects this date format
start: "20090101T00:00:01Z" # yyyymmddThh:mm:ssZ
end: "NOW" # yyyymmddThh:mm:ssZ for specific date or "NOW" for...now 
user: anonymous # does not change
host: https://podaac.jpl.nasa.gov/ws/search/granule/?format=atom&pretty=false&itemsPerPage=300000 # does not change
date_regex: "%Y-%m-%dT%H:%M:%SZ" # does not change

# =====================================================
# Dataset
# =====================================================
ds_name: "obp_GRC-GFO_GRIDDED_AOD1B_JPL_MASCON_RL06" # Name for dataset
harvester_type: "podaac"
podaac_id: "PODAAC-GGAOD-3MJ60"
aggregated: false # if data is available aggregated
data_time_scale: "monthly" # daily or monthly
date_format: "yyyyddd" # format of date in file name ex: yyyymmdd
fields:
  [
    {
      name: "GAB_msc_Lmax180",
      long_name: "GAB mascon; degree Lmax180",
      standard_name: " ",
      units: "meters_Liquid_Water_Equivalent_Thickness",
    },
    {
      name: "GAD_msc_Lmax180",
      long_name: "GAD mascon; degree Lmax180",
      standard_name: " ",
      units: "meters_Liquid_Water_Equivalent_Thickness",
    },
  ]

# new_data_attrs:
original_dataset_title: "JPL GRACE/GRACE-FO Gridded-AOD1B Water-Equivalent-Thickness Surface-Mass Anomaly RL06 dataset for Tellus Level-3 mascon 0.5-degree grid"
original_dataset_short_name: "GRC-GFO_GRIDDED_AOD1B_JPL_MASCON_RL06"
original_dataset_url: "https://podaac.jpl.nasa.gov/dataset/GRC-GFO_GRIDDED_AOD1B_JPL_MASCON_RL06"
original_dataset_reference: "https://doi.org/10.5067/GGAOD-3MJ60"
original_dataset_doi: "10.5067/GGAOD-3MJ60"

# =====================================================
# Solr
# =====================================================
solr_host_local: http://localhost:8983/solr/ # doesn't change if following standard Solr setup
solr_host_aws: http://ec2-3-16-187-19.us-east-2.compute.amazonaws.com:8983/solr/
solr_collection_name: ecco_datasets # doesn't change

# =====================================================
# AWS
# =====================================================
target_bucket_name: ecco-preprocess
