# =====================================================
# PODAAC
# =====================================================
# PODAAC explicitly expects this date format
start: "20060101T00:00:00Z" # yyyymmddThh:mm:ssZ
end: "NOW" # yyyymmddThh:mm:ssZ for specific date or "NOW" for...now 
user: anonymous # does not change
host: https://podaac.jpl.nasa.gov/ws/search/granule/?format=atom&pretty=false&itemsPerPage=300000 # does not change
date_regex: "%Y-%m-%dT%H:%M:%SZ" # does not change

# =====================================================
# Dataset
# =====================================================
ds_name: "ewh_TELLUS_GRAC-GRFO_MASCON_CRI_GRID_RL06_V2" # Name for dataset
harvester_type: "podaac"
podaac_id: "PODAAC-TEMSC-3JC62"
aggregated: true # if data is available aggregated
data_time_scale: "monthly" # daily or monthly
date_format: "yyyymm" # format of date in file name ex: yyyymmdd
fields: [{ name: "lwe_thickness", long_name: "Liquid_Water_Equivalent_Thickness", standard_name: "Liquid_Water_Equivalent_Thickness", units: "cm" },
{ name: "uncertainty", long_name: "uncertainty", standard_name: "uncertainty", units: "cm" }
]

# new_data_attrs:
original_dataset_title: "JPL GRACE and GRACE-FO Mascon Ocean, Ice, and Hydrology Equivalent Water Height Coastal Resolution Improvement (CRI) Filtered Release 06 Version 02"
original_dataset_short_name: "TELLUS_GRAC-GRFO_MASCON_CRI_GRID_RL06_V2"
original_dataset_url: "https://podaac.jpl.nasa.gov/dataset/TELLUS_GRAC-GRFO_MASCON_CRI_GRID_RL06_V2?ids=&values=&search=mascon"
original_dataset_reference: "https://podaac.jpl.nasa.gov/GRACE"
original_dataset_doi: "10.5067/TEMSC-3JC62"

# =====================================================
# Solr
# =====================================================
solr_host_local: http://localhost:8983/solr/ # doesn't change if following standard Solr setup
solr_host_aws: http://ec2-3-16-187-19.us-east-2.compute.amazonaws.com:8983/solr/
solr_collection_name: ecco_datasets # doesn't change

# =====================================================
# AWS
# =====================================================
target_bucket_name: ecco-preprocess
