# =====================================================
# Dataset
# =====================================================
ds_name: "seaice_AMSR-2" # Name for dataset
version: 1.0
array_precision: float32
time_zone_included_with_time: False # Data time values have time zone
extra_information: ['time_bounds_var', 'time_var'] # Unique things to do for dataset
data_res: "10/111" # Resolution of dataset

# Values for non split datasets
# data_max_lat: 90.0 # Maximum latitude in dataset
# area_extent: [] # [lon_min, lat_min, lon_max, lat_max]
# dims: [] # [lon, lat]
# proj_info:
#   {
#     "area_id": "longlat",
#     "area_name": "Plate Carree",
#     "proj_id": "EPSG:4326",
#     "proj4_args": "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs",
#   }

# Uncomment below lines and fill in with necessary information
# if data is stored separately by hemisphere
data_max_lat_nh: 90.0
data_max_lat_sh: -90.0

area_extent_nh: [-3845000, -5345000, 3745000, 5845000]
area_extent_sh: [-3950000, -3950000, 3945000, 4340000]

dims_nh: [760, 1120]
dims_sh: [790, 830]

proj_info_nh:
  {
    "area_id": "3411",
    "area_name": "polar_stereographic",
    "proj_id": "3411",
    "proj4_args": "+init=EPSG:3411",
  }
proj_info_sh:
  {
    "area_id": "3412",
    "area_name": "polar_stereographic",
    "proj_id": "3412",
    "proj4_args": "+init=EPSG:3412",
  }

extra_transformation_steps: [] # Additional full dataset transformation steps

# =====================================================
# Solr
# =====================================================
solr_host_local: http://localhost:8983/solr/ # doesn't change if following standard Solr setup
solr_host_aws: http://ec2-3-16-187-19.us-east-2.compute.amazonaws.com:8983/solr/
solr_collection_name: ecco_datasets # doesn't change

# =====================================================
# Local
# =====================================================
# REMEMBER, REPLACE LOCAL PATHS SO THEY POINT TO YOUR /SRC/ DIRECTORY
output_dir: /Users/kevinmarlis/Developer/JPL/ecco-preprocessing/src/output/
ecco_utils: /Users/kevinmarlis/Developer/JPL/ecco-access/ECCO-ACCESS/ecco-cloud-utils/

# =====================================================
# AWS
# =====================================================
source_bucket: ecco-preprocess
target_bucket: ecco-ames
aws_output_dir: seaice_AMSR-2_transformed/


