# =====================================================
# NSIDC - RDEFT4
# =====================================================
# Data is recorded from September - April
# Data files are named with the end date of the rolling average
start: "1980-01-01T00:00:00Z"
end: "NOW" # yyyymmddThh:mm:ssZ for specific date or "NOW" for...now 
date_regex: "%Y-%m-%dT%H:%M:%SZ"
regex: '\d{8}'

# =====================================================
# Dataset
# =====================================================
ds_name: "seaice_conc_RDEFT4"
harvester_type: "nsidc_ftp"
aggregated: false
data_time_scale: "monthly"
date_format: yyyymmdd
fields:
  [
    {
      name: sea_ice_thickness,
      long_name: Sea ice thickness,
      standard_name: " ",
      units: Meters,
    },
    {
      name: snow_depth,
      long_name: Snow depth,
      standard_name: " ",
      units: Meters,
    },
    {
      name: freeboard,
      long_name: Ice freeboard,
      standard_name: " ",
      units: Meters,
    },
  ]

# new_data_attrs:
original_dataset_title: CryoSat-2 Level-4 Sea Ice Elevation, Freeboard, and Thickness, Version 1
original_dataset_short_name: seaice_conc_RDEFT4
original_dataset_url: https://nsidc.org/data/RDEFT4
original_dataset_reference: https://doi.org/10.5067/96JO0KIFDAS8
original_dataset_doi: 10.5067/96JO0KIFDAS8

# =====================================================
# Solr
# =====================================================
solr_host_local: http://localhost:8983/solr/ # doesn't change if following standard Solr setup
solr_host_aws: http://ec2-3-16-187-19.us-east-2.compute.amazonaws.com:8983/solr/
solr_collection_name: ecco_datasets # doesn't change

# =====================================================
# AWS
# =====================================================
target_bucket_name: ecco-preprocess
