# =====================================================
# PODAAC
# =====================================================
# PODAAC explicitly expects this date format
start: "19800101T00:00:01Z" # yyyymmddThh:mm:ssZ
end: "NOW" # yyyymmddThh:mm:ssZ for specific date or "NOW" for...now
user: anonymous # does not change
host: https://podaac.jpl.nasa.gov/ws/search/granule/?format=atom&pretty=false&itemsPerPage=300000 # does not change
date_regex: "%Y-%m-%dT%H:%M:%SZ" # does not change

# =====================================================
# Dataset
# =====================================================
ds_name: "obp_TELLUS_GRFO_L3_JPL_RL06_OCN_v04" # Name for dataset
harvester_type: "podaac"
podaac_id: "PODAAC-GFOCN-3AJ64"
aggregated: false # if data is available aggregated
data_time_scale: "monthly" # daily or monthly
date_format: "yyyyddd" # format of date in file name ex: yyyymmdd
fields:
  [
    {
      name: "lwe_thickness",
      long_name: "Liquid_Water_Equivalent_Thickness",
      standard_name: "Liquid_Water_Equivalent_Thickness",
      units: "m",
    },
  ]

# new_data_attrs:
original_dataset_title: "JPL TELLUS GRACE-FO Level-3 Monthly Ocean Bottom Pressure Anomaly Release 6.0 version 04 in netCDF/ASCII/GeoTIFF Formats"
original_dataset_short_name: "TELLUS_GRFO_L3_JPL_RL06_OCN_v04"
original_dataset_url: "https://podaac.jpl.nasa.gov/dataset/TELLUS_GRFO_L3_JPL_RL06_OCN_v04"
original_dataset_reference: "https://gracefo.jpl.nasa.gov/"
original_dataset_doi: "10.5067/GFOCN-3AJ64"

# =====================================================
# Solr
# =====================================================
solr_host_local: http://localhost:8983/solr/ # doesn't change if following standard Solr setup
solr_host_aws: http://ec2-3-16-187-19.us-east-2.compute.amazonaws.com:8983/solr/
solr_collection_name: ecco_datasets # doesn't change

# =====================================================
# AWS
# =====================================================
target_bucket_name: ecco-preprocess
