# =====================================================
# PODAAC
# =====================================================
# PODAAC explicitly expects this date format
start: "19800101T00:00:00Z" # yyyymmddThh:mm:ssZ
end: "NOW" # yyyymmddThh:mm:ssZ for specific date or "NOW" for...now
user: anonymous # does not change
host: https://podaac.jpl.nasa.gov/ws/search/granule/?format=atom&pretty=false&itemsPerPage=300000 # does not change
date_regex: "%Y-%m-%dT%H:%M:%SZ" # does not change

# =====================================================
# Dataset
# =====================================================
ds_name: "sst_MODIS_AQUA_L3_9KM" # Name for dataset
harvester_type: "podaac"
podaac_id: "PODAAC-MODSA-1D9D9"
aggregated: false # if data is available aggregated
data_time_scale: "daily" # daily or monthly
date_format: "yyyymmdd" # format of date in file name ex: yyyymmdd
fields:
  [
    {
      name: sst,
      long_name: Sea Surface Temperature,
      standard_name: sea_surface_temperature,
      units: degree_C,
    },
    {
      name: qual_sst,
      long_name: "Quality Levels, Sea Surface Temperature",
      standard_name: " ",
      units: " ",
    },
  ]

# new_data_attrs:
original_dataset_title: MODIS Aqua Level 3 SST Thermal IR Daily 9km Daytime V2019.0
original_dataset_short_name: MODIS_AQUA_L3_SST_THERMAL_DAILY_9KM_DAYTIME_V2019.0
original_dataset_url: https://podaac.jpl.nasa.gov/dataset/MODIS_AQUA_L3_SST_THERMAL_DAILY_9KM_DAYTIME_V2019.0
original_dataset_reference: http://oceancolor.gsfc.nasa.gov
original_dataset_doi: 10.5067/MODSA-1D9D9

# =====================================================
# Solr
# =====================================================
solr_host_local: http://localhost:8983/solr/ # doesn't change if following standard Solr setup
solr_host_aws: http://ec2-3-16-187-19.us-east-2.compute.amazonaws.com:8983/solr/
solr_collection_name: ecco_datasets # doesn't change

# =====================================================
# AWS
# =====================================================
target_bucket_name: ecco-preprocess
